import { Platform } from 'react-native';
import type { MarkdownStyle } from 'react-native-enriched-markdown';

export const customMarkdownStyle: MarkdownStyle = {
  paragraph: {
    fontSize: 15,
    color: '#1f2937',
    lineHeight: Platform.select({
      macos: 22,
      ios: 22,
      android: 24,
      default: 22,
    }),
    marginBottom: 14,
  },
  h1: {
    fontSize: 28,
    color: '#111827',
    lineHeight: Platform.select({
      macos: 34,
      ios: 34,
      android: 36,
      default: 34,
    }),
    marginBottom: 8,
  },
  h2: {
    fontSize: 22,
    color: '#111827',
    lineHeight: Platform.select({
      macos: 28,
      ios: 28,
      android: 30,
      default: 28,
    }),
    marginBottom: 8,
  },
  h3: {
    fontSize: 18,
    color: '#1f2937',
    lineHeight: Platform.select({
      macos: 24,
      ios: 24,
      android: 26,
      default: 24,
    }),
    marginBottom: 8,
  },
  h4: {
    fontSize: 16,
    color: '#1f2937',
    lineHeight: Platform.select({
      macos: 22,
      ios: 22,
      android: 24,
      default: 22,
    }),
    marginBottom: 8,
  },
  h5: {
    fontSize: 14,
    color: '#374151',
    lineHeight: Platform.select({
      macos: 20,
      ios: 20,
      android: 22,
      default: 20,
    }),
    marginBottom: 8,
  },
  h6: {
    fontSize: 13,
    color: '#4b5563',
    lineHeight: Platform.select({
      macos: 18,
      ios: 18,
      android: 20,
      default: 18,
    }),
    marginBottom: 8,
  },
  blockquote: {
    fontSize: 15,
    color: '#4b5563',
    lineHeight: Platform.select({
      macos: 22,
      ios: 22,
      android: 24,
      default: 22,
    }),
    borderColor: '#d1d5db',
    borderWidth: 3,
    backgroundColor: '#f9fafb',
    gapWidth: 14,
    marginBottom: 14,
  },
  list: {
    fontSize: 15,
    color: '#1f2937',
    lineHeight: Platform.select({
      macos: 20,
      ios: 20,
      android: 24,
      default: 20,
    }),
    bulletColor: '#6b7280',
    bulletSize: 5,
    markerColor: '#6b7280',
    markerFontWeight: '500',
    gapWidth: 8,
    marginLeft: 20,
    marginBottom: 14,
  },
  codeBlock: {
    fontFamily: 'Menlo',
    fontSize: 13,
    color: '#f3f4f6',
    backgroundColor: '#1f2937',
    borderColor: '#374151',
    borderWidth: 1,
    borderRadius: 6,
    padding: 14,
    lineHeight: Platform.select({
      macos: 19,
      ios: 19,
      android: 21,
      default: 19,
    }),
    marginBottom: 14,
  },
  code: {
    fontFamily: 'Menlo',
    color: '#7c3aed',
    backgroundColor: '#f5f3ff',
    borderColor: '#ddd6fe',
  },
  link: {
    color: '#2563eb',
    underline: true,
  },
  strong: {
    color: '#111827',
  },
  em: {
    color: '#4b5563',
  },
  image: {
    height: 200,
    borderRadius: 8,
    marginBottom: 14,
  },
  inlineImage: {
    size: 18,
  },
  thematicBreak: {
    color: '#e5e7eb',
    height: 1,
    marginTop: 20,
    marginBottom: 20,
  },
  table: {
    fontFamily: 'Menlo',
    fontSize: 13,
    color: '#1f2937',
    lineHeight: Platform.select({
      macos: 18,
      ios: 18,
      android: 20,
      default: 18,
    }),
    marginBottom: 14,
    headerBackgroundColor: '#f3f4f6',
    headerTextColor: '#111827',
    rowEvenBackgroundColor: '#ffffff',
    rowOddBackgroundColor: '#f9fafb',
    borderColor: '#e5e7eb',
    borderRadius: 6,
    cellPaddingHorizontal: 10,
    cellPaddingVertical: 6,
  },
  taskList: {
    checkedColor: '#2563eb',
    borderColor: '#9ca3af',
    checkboxSize: 16,
    checkboxBorderRadius: 3,
    checkmarkColor: '#ffffff',
    checkedTextColor: '#9ca3af',
    checkedStrikethrough: true,
  },
};
